### ISSUE TITLE
As a User, I want to Register on the EarthCODE portal , so that I can be authenticated by the portal in the future

### ISSUE THREAD

**Issue by GarinSmith** [ESA-EarthCODE/EarthCODE#21]

**Comment by GarinSmith** [comment]
.

**Comment by GarinSmith** [comment]
.

**Comment by Schpidi** [comment]
Work is ongoing in the `testing` branch of the portal including the login/register button with the goal to publicly release within September. This can be reviewed at https://testing.earthcode.eox.at/
