### ISSUE TITLE
As a Admin, I want to Publish an experiment/workflow in GitHub , so that it is ingested into the EarthCODE Catalogue (OSC)

### ISSUE THREAD

**Issue by GarinSmith** [ESA-EarthCODE/EarthCODE#29]
**Done Criteria**
An Admin user can accept a merge request for an experiment or workflow in GitHub (OGC API Records schema) that is ingested into the catalogue 
This applies to 
-  CDSE openEO  
-  EOX - Euro Data Cube
-  DeepESDL

I have added this to help with sign off.

**Comment by GarinSmith** [comment]
Hi @Schpidi and @silvester-pari , 
This is the most important user story we would like to demo tomorrow.
As discussed this could be demonstrated using the example Vito experiment to show that it is Findable in the Catalog.
This will probably also close off some other dependent stories (especially if you also demo an EDC experiment). 
If you add a link to the Findable Vito experiment here, I can also demo this tomorrow if needed. 
This is a key enabler to the planned milestone, so it would be great if we can demo this.

**Comment by Schpidi** [comment]
git-clerk deployed in [staging env](https://dashboard.earthcode-staging.earthcode.eox.at/) for demo and review

**Comment by GarinSmith** [comment]
Hi @Schpidi , 
I had a look at the link above.  I could login and got the message, "Welcome to EarthCODE [staging], Garin!"
However, that was all I could see, do I need to submit a pull request (or use GitClerk) to see something more?
I am happy to test further with some more guidance.

**Comment by Schpidi** [comment]
Hi @GarinSmith, you should see the Catalog Editor like this:

![Image](https://github.com/user-attachments/assets/8f9580b1-12e6-46da-9d2c-3c3facba3b47)

Could you please post a screenshot if you see something else? Thanks

**Comment by GarinSmith** [comment]
Hi @Schpidi ,
I can now see the same thing as you (I think this is different to last time, maybe something changed).
I clicked on Blog and Catalog editor and authorized both of them using  GarinSmith and then also ESA-EarthCODE.
However, the authorise dialog box does not go away, so I cannot proceed further (even after authorising as above). 
I will add a screen hot.  
![Image](https://github.com/user-attachments/assets/e3fe4f72-e0f5-4939-970f-237897de542f)
Any ideas?

**Comment by Schpidi** [comment]
When you click oh the "Authorize EarthCODE OSC Editor" button you're redirected to GitHub in a popup where you'd need to grant access to the GitHub App for your personal organization and all repositories as git-clerk is going to create a fork there.

**Comment by GarinSmith** [comment]
I did this before.  I just logged in again.   
This time I was asked for a session name and when I provided one I got the screen below. 

I then created and save a new experiment. 

![Image](https://github.com/user-attachments/assets/dfd969f8-0149-4087-ad85-d83b2f95e2c7)

**Comment by GarinSmith** [comment]
Hi @Schpidi and @silvester-pari , 
Can you please add a link to the experiment that was published?  I think Stephan said this included an OGC API Processes Application Package.  

I am interested in referencing a useful example EarthCODE experiment OGC API Processes Application Package.
Maybe we could then ask EOEPCA+ to use their demo instance to deploy and execute this real world experiment.  This could be used in a number of ways including to: 
i) Prove an experiment is portable
ii) Prove EOEPCA+ can reproduce it on it's demo platform
iii) Demo EOEPCA+ can provide solutions to execute algorithms and access the data needed.
iv) Allow EOEPCA+ to demo federation concepts for say OGC API Processes Application Package / Open EO federation.
v) Allow EOEPCA+ to demo other federation concepts based upon this.
vii) Maybe provide a reference to allow EarthCODE platforms to be support reproducibility.
These are just general ideas for consideration at the moment and to help us guide what we want from EOEPCA+.
