### ISSUE TITLE
As a Platform, I want to Confirm that I can use the EarthCODE OGC API Records Schema , so that I can publish experiment/workflows in the future

### ISSUE THREAD

**Issue by GarinSmith** [ESA-EarthCODE/EarthCODE#34]
Provide a working validated example

{
   "id":"4Dmed_hydrology_cube_generation",
   "type":"Feature",
   "conformsTo":[
      "http://www.opengis.net/spec/ogcapi-records-1/1.0/req/record-core"
   ],
   "time":{
      "interval":[
         "2024-01-01T00:00:00Z",
         ".."
      ]
   },
   "geometry":null,
   "properties":{
      "created":"2024-11-19T00:00:00Z",
      "updated":"2024-11-19T00:00:00Z",
      "type":"workflow",
      "title":"Hydrology Datacube Generation",
      "description":"A workflow to generate a 4DMed Hydrology Datacube.",
      "jupyter-kernel":{
         "name":"deepesdl-xcube-1.7.1",
         "pythonVersion":3.11
      },
      "keywords":[
         "evaporation",
         "precipitation"
      ],
      "contacts":[
         {
            "name":"Tejas Morbagal Harish",
            "organization":"Brockmann Consult GmbH"
         },
         {
            "name":"Brockmann Consult GmbH",
            "organization":"Brockmann Consult GmbH",
            "links":[
               {
                  "href":"https://www.brockmann-consult.de/",
                  "rel":"about",
                  "type":"text/html"
               }
            ],
            "contactInstructions":"SEE WEBSITE",
            "roles":[
               "processor"
            ]
         }
      ],
      "themes":[
         {
            "concepts":[
               {
                  "id":"PRECIPITATION"
               },
               {
                  "id":"EVAPORATION"
               },
               {
                  "id":"SOIL MOISTURE"
               },
               {
                  "id":"SNOW WATER EQUIVALENT"
               }
            ],
            "scheme":"https://gcmd.earthdata.nasa.gov/kms/concepts/concept_scheme/sciencekeywords"
         }
      ],
      "formats":[
         {
            "name":"zarr"
         }
      ],
      "license":"other"
   },
   "linkTemplates":[],
   "links":[
      {
         "rel":"documentation",
         "type":"application/json",
         "title":"4DMed Hydrology Cube Generation Recipe",
         "href":"https://github.com/deepesdl/cube-gen/tree/main/hydrology/README.md"
      },
      {
         "rel":"jupyter-notebook",
         "type":"application/json",
         "title":"Python Process Title",
         "href":"https://github.com/deepesdl/cube-gen/blob/main/hydrology/notebooks/reading_hydrology.ipynb"
      },
      {
         "rel":"python-process",
         "type":"application/json",
         "title":"Python Process Title",
         "href":"https://github.com/deepesdl/cube-gen/blob/main/hydrology/output-merge/daily_aggregates_and_merge.py"
      }
   ]
}

**Comment by TejasMorbagal** [comment]
check-jsonschema --schemafile wcmp2-bundled.json ogc-api-record-example.json
ok -- validation done
