### ISSUE TITLE
As a VITO Platform, I want to Confirm that I can use the EarthCODE OGC API Records Schema , so that I can publish experiment/workflows in the future

### ISSUE THREAD

**Issue by JanssenBrm** [ESA-EarthCODE/EarthCODE#5]
Provide a working validated example

**Comment by JanssenBrm** [comment]
Created ticket for follow-up: https://github.com/eu-cdse/openeo-cdse-infra/issues/302

**Comment by JanssenBrm** [comment]
An example is available at : https://github.com/ESA-APEx/apex_algorithms/blob/main/algorithm_catalog/worldcereal_inference.json

**Comment by soxofaan** [comment]
We have even more examples in that APEx algorithms repo of OGC records pointing to openEO process definitions (aka UDPs): https://github.com/ESA-APEx/apex_algorithms/tree/main/algorithm_catalog

**Comment by GarinSmith** [comment]
Hi @soxofaan , 
Thanks, this looks good. 
Can you please confirm if they all validate against the EarthCODE schema?
E.g. https://github.com/EOEPCA/metadata-profile/tree/master/schemas
Please see architecture document for more details.

**Comment by GarinSmith** [comment]
Hi @soxofaan, 

I had a quick look at this and tested  bap_composite.json at random. 
Using 
check-jsonschema --schemafile resource.json bap_composite.json          // I think we need a better name for resource.json by the way
I got 
Schema validation errors were encountered.
  bap_composite.json::$: 'geometry' is a required property
  bap_composite.json::$.properties.formats[0]: 'GeoTiff' is not of type 'object'
  bap_composite.json::$.properties.formats[1]: 'netCDF' is not of type 'object'
  bap_composite.json::$.properties.type: 'apex_algorithm' is not one of ['dataset', 'service', 'process', 'workflow']

However these were easily fixed using the approach we used for worldcereal_inference.json before
E.g.
check-jsonschema --schemafile resource.json bap_composite_v2.json 
ok -- validation done

See attached.  

Does this approach seem reasonable to you?

[bap_composite_v2.json](https://github.com/user-attachments/files/17779038/bap_composite_v2.json)

**Comment by soxofaan** [comment]
Hi @GarinSmith 

I already fixed most of these issues with https://github.com/ESA-APEx/apex_algorithms/commit/cd199d370caff390446ab903f76f445e9e56da1b and https://github.com/ESA-APEx/apex_algorithms/commit/945b0289f28bf5584ac2910c8c0aac1f42c11115

One thing I'm however not sure about is changing `properties.type` from "apex_algorithm" to "process"`. We intentionally chose "apex_algorithm"  to be very explicit what's it about. With "process" you loose that specificity, making it very generic. This probably requires some more thought

> check-jsonschema --schemafile resource.json

I assume you are using the tool https://github.com/python-jsonschema/check-jsonschema here, but can you give me an exact pointer to that schema file?

**Comment by soxofaan** [comment]
> can you give me an exact pointer to that schema file?

nevermind, I guess it can be found  at https://github.com/EOEPCA/metadata-profile/tree/master/schemas , is that correct?

**Comment by soxofaan** [comment]
FYI current validation only complains about that "type" issue mentioned above:

> $ uv tool run check-jsonschema --schemafile EarthCODE/metadata-profile/schemas/resource.json  APEx/apex_algorithms/algorithm_catalog/bap_composite.json
> Schema validation errors were encountered.
>   APEx/apex_algorithms/algorithm_catalog/bap_composite.json::$.properties.type: 'apex_algorithm' is not one of ['dataset', 'service', 'process', 'workflow']

**Comment by soxofaan** [comment]
As discussed in the EarthCODE meeting today, I raised the "properties.type" related questions in the relevant repo's:
- https://github.com/EOEPCA/metadata-profile/issues/1
- https://github.com/ESA-APEx/apex_algorithms/issues/65
